import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { Content, works } from '../contents/contents'
import styles from '../styles/Home.module.css'

const Work = dynamic(async () => {
  const importedModule = await import('../components/Work')
  return importedModule.Work
}, {ssr: false})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          {/* Hi. I&apos;m ritar. */}
          こんにちは。
        </h1>
        <section className={styles.first}>
          <p>
            ritarと申します。<br />
            東京大学大学院 情報理工学系研究科 葛岡雨宮鳴海研究室に所属しています。<br />
          </p>
        </section>

        <section className={styles.works}>
          <div className={styles.divider}></div>
          <h2>Works</h2>
          {works.map((e: Content) => {
            return <Work e={e} key={e.title}/>
          })}
        </section>
      </main>

      <footer className={styles.footer}>
          <p>Copyright statements goes here.</p>
      </footer>
    </div>
  )
}

export default Home
