import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Content, works } from '../contents/contents'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          {/* Hi. I&apos;m ritar. */}
          こんにちは。
        </h1>
        <section className={styles.first}>
          <p>
            ritarと申します。<br />
            東京大学大学院 情報理工学系研究科 葛岡雨宮鳴海研究室に所属しています。<br />
          </p>
        </section>

        <section className={styles.works}>
          <div className={styles.divider}></div>
          <h2>Works</h2>
          {works.map((e: Content) => {
            return <section className={styles.work} key={e.title}>
              <h3>{e.title}</h3>
              <a href={e.link}>Link</a>
              <p>{e.desc}</p>
              {e.img && 
                <div className={styles.img}>
                  <Image src={e.img} alt='description image' layout='fill' objectFit='contain' />
                </div>
              }
            </section>
          })}
        </section>
      </main>

      <footer className={styles.footer}>
          <p>Copyright statements goes here.</p>
      </footer>
    </div>
  )
}

export default Home
